# Generated by Django 5.0.9 on 2025-07-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv_builder", "0002_pdfgenerationlog_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cvprofile",
            name="user_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="pdfgenerationlog",
            name="user_id",
            field=models.IntegerField(),
        ),
    ]
